/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary": "#5d5f5f",
        "surface-bright": "#fcf8f8",
        "on-secondary": "#ffffff",
        "surface": "#fcf8f8",
        "error-container": "#ffdad6",
        "on-background": "#1c1b1b",
        "inverse-on-surface": "#f4f0ef",
        "on-tertiary-container": "#747676",
        "surface-tint": "#5d5f5f",
        "on-tertiary": "#ffffff",
        "on-secondary-container": "#586377",
        "surface-container-lowest": "#ffffff",
        "on-primary": "#ffffff",
        "primary-fixed": "#e2e2e2",
        "on-primary-fixed-variant": "#454747",
        "outline": "#747878",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "surface-container-high": "#ebe7e7",
        "primary-fixed-dim": "#c6c6c7",
        "surface-container-highest": "#e5e2e1",
        "surface-container": "#f1edec",
        "on-primary-fixed": "#1a1c1c",
        "secondary-container": "#d5e0f8",
        "on-surface": "#1c1b1b",
        "on-surface-variant": "#444748",
        "tertiary-container": "#ffffff",
        "tertiary-fixed-dim": "#c6c6c7",
        "on-secondary-fixed-variant": "#3c475a",
        "outline-variant": "#c4c7c8",
        "on-error-container": "#93000a",
        "background": "#fcf8f8",
        "primary-container": "#ffffff",
        "inverse-surface": "#313030",
        "surface-dim": "#ddd9d9",
        "primary": "#5d5f5f",
        "surface-container-low": "#f6f3f2",
        "secondary": "#545f73",
        "on-tertiary-fixed": "#1a1c1c",
        "surface-variant": "#e5e2e1",
        "secondary-fixed": "#d8e3fb",
        "inverse-primary": "#c6c6c7",
        "secondary-fixed-dim": "#bcc7de",
        "tertiary-fixed": "#e2e2e2",
        "on-primary-container": "#747676",
        "on-secondary-fixed": "#111c2d",
        "on-tertiary-fixed-variant": "#454747",
        "brand-emerald": "#10B981"
      },
      spacing: {
        "base": "8px",
        "margin-mobile": "16px",
        "gutter": "24px",
        "container-max": "1280px",
        "margin-desktop": "48px"
      },
      fontFamily: {
        "headline-lg": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "display": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"]
      }
    },
  },
  plugins: [],
}
