spring.application.name=Sistema_Cancha

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=reserva_canchas;encrypt=true;trustServerCertificate=true;sendTimeAsDatetime=false;
spring.datasource.username=jafigueroa
spring.datasource.password=abc123...
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Hibernate ddl-auto configurado en validate o none ya que la BD ya existe
spring.jpa.hibernate.ddl-auto=none
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
